services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datathon-mlet
    working_dir: /app
    volumes:
      - mlflow_db:/app/mlflow   # pasta que contém mlflow.db
      - mlruns_data:/app/mlruns # pasta de artifacts
    command: dvc repro

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datathon-mlflow-ui
    working_dir: /app
    volumes:
      - mlflow_db:/app/mlflow   # pasta que contém mlflow.db
      - mlruns_data:/app/mlruns # pasta de artifacts
    ports:
      - "5000:5000"
    command: >
      mlflow ui
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow/mlflow.db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datathon-mlet-api
    working_dir: /app
    volumes:
      - mlflow_db:/app/mlflow   # pasta que contém mlflow.db
      - mlruns_data:/app/mlruns # pasta de artifacts
    ports:
      - "8000:8000"
    command: uvicorn src.serving.app:app --host "0.0.0.0" --port 8000

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: datathon-mlet-test
    working_dir: /app
    volumes:
      - .:/app
    command: pytest -v

volumes:
  mlflow_db:
  mlruns_data: