FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir bentoml vllm

COPY ./bentos /bentos

EXPOSE 3000

CMD ["bentoml", "serve", "/bentos"]