FROM python:3.10-slim

WORKDIR /app

# Instala dependências
COPY ../pyproject.toml ../poetry.lock* ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir poetry && \
    poetry install --no-root

# Copia o código da aplicação
COPY ../app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]