FROM python:3.10-slim

WORKDIR /app

# Copia o requirements.txt e instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copia o código do serviço BentoML
COPY generator/serving /generator/serving

EXPOSE 3000

CMD ["bentoml", "serve", "/generator/serving"]