FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir bentoml vllm requests

# Copia o serviço BentoML
COPY generator/serving /generator/serving

EXPOSE 3000

CMD ["bentoml", "serve", "/generator/serving"]